[package]
name = "multithreaded_benchmark"
authors = ["Carl Wachter"]
edition = "2021"

[dependencies]
hermit_bench_output = "0.1.0"

[target.'cfg(target_os = "hermit")'.dependencies]
hermit = { path = "../../hermit", default-features = false }

[features]
