[package]
name = "nvme-test"
authors = ["Valentin Kunisch <v.qnish@protonmail.com>"]
edition = "2024"

[target.'cfg(target_os = "hermit")'.dependencies]
hermit = { path = "../../hermit", default-features = false }

[features]
default = ["hermit/acpi", "hermit/fs", "hermit/pci"]
